from __future__ import annotations

import json
import os
from dataclasses import asdict
from datetime import UTC, datetime
from typing import Any

import psycopg
from psycopg import Connection
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

from app.services import CandidateLead, RenderedEmail, ReplyAnalysis, infer_lead_type


# ── Connection pool ────────────────────────────────────
#
# The app talks to PostgreSQL through a process-wide connection pool. Every DB
# helper uses `with connect() as connection:` - the pool hands out a connection,
# and on clean block exit the transaction commits (rolls back on exception) and
# the connection returns to the pool. This gives proper concurrency for the
# threadpool FastAPI runs sync endpoints in.

def _conninfo() -> str:
    """Resolve the PostgreSQL connection string.

    Prefers a full DSN in MEDBOT_DATABASE_URL; otherwise assembles one from
    discrete MEDBOT_DB_* parts (handy in compose where they're set separately).
    """
    url = os.getenv("MEDBOT_DATABASE_URL", "").strip()
    if url:
        return url
    host = os.getenv("MEDBOT_DB_HOST", "postgres")
    port = os.getenv("MEDBOT_DB_PORT", "5432")
    name = os.getenv("MEDBOT_DB_NAME", "medbot")
    user = os.getenv("MEDBOT_DB_USER", "medbot")
    password = os.getenv("MEDBOT_DB_PASSWORD", "medbot")
    return f"host={host} port={port} dbname={name} user={user} password={password}"


_pool: ConnectionPool | None = None


def _get_pool() -> ConnectionPool:
    global _pool
    if _pool is None:
        _pool = ConnectionPool(
            conninfo=_conninfo(),
            min_size=1,
            max_size=int(os.getenv("MEDBOT_DB_POOL_MAX", "10")),
            kwargs={"row_factory": dict_row},
            open=True,
        )
    return _pool


def _reset_pool() -> None:
    """Close and drop the pool (tests use this to rebind to a fresh DSN)."""
    global _pool
    if _pool is not None:
        try:
            _pool.close()
        finally:
            _pool = None


def connect():
    """Return a pooled connection context manager (`with connect() as conn:`)."""
    return _get_pool().connection()


def _scalar(cursor: psycopg.Cursor) -> Any:
    """Read the first column of the first row (dict rows have no positional [0])."""
    row = cursor.fetchone()
    if row is None:
        return None
    return next(iter(row.values()))


_SCHEMA_DDL = """
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    region TEXT NOT NULL,
    country TEXT NOT NULL,
    website TEXT NOT NULL,
    contact_name TEXT NOT NULL,
    email TEXT NOT NULL,
    category TEXT NOT NULL,
    match_reason TEXT NOT NULL,
    source TEXT NOT NULL,
    score INTEGER NOT NULL,
    status TEXT NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    lead_type TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS outreach_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    sent_to TEXT NOT NULL,
    region TEXT NOT NULL,
    status TEXT NOT NULL,
    message_id TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT 'manual',
    attach_brochure INTEGER NOT NULL DEFAULT 0,
    sent_at TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    FOREIGN KEY (lead_id) REFERENCES leads(id)
);

CREATE TABLE IF NOT EXISTS reply_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT,
    reply_text TEXT NOT NULL,
    intent TEXT NOT NULL,
    confidence REAL NOT NULL,
    summary TEXT NOT NULL,
    next_action TEXT NOT NULL,
    requires_human INTEGER NOT NULL,
    message_id TEXT NOT NULL DEFAULT '',
    draft_pending INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    FOREIGN KEY (lead_id) REFERENCES leads(id)
);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    display_name TEXT NOT NULL DEFAULT '',
    is_active INTEGER NOT NULL DEFAULT 1,
    is_superadmin INTEGER NOT NULL DEFAULT 0,
    must_change_password INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT '',
    permissions TEXT NOT NULL DEFAULT '[]',
    is_system INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS suppressions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    reason TEXT NOT NULL DEFAULT 'unsubscribe',
    source TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor TEXT NOT NULL DEFAULT '',
    action TEXT NOT NULL,
    target_type TEXT NOT NULL DEFAULT '',
    target_id TEXT NOT NULL DEFAULT '',
    detail TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS token_usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    provider TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT '',
    prompt_tokens INTEGER NOT NULL DEFAULT 0,
    completion_tokens INTEGER NOT NULL DEFAULT 0,
    total_tokens INTEGER NOT NULL DEFAULT 0,
    actor TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);

-- Agent chat is TEAM-SHARED: sessions and turns live server-side (not in each
-- browser's localStorage), so history follows the deployment, not the machine.
-- Every user with agent.use sees the same pool; `created_by` / `author` record
-- who said what.
CREATE TABLE IF NOT EXISTS agent_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL DEFAULT '',
    created_by TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_turns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    author TEXT NOT NULL DEFAULT '',
    payload TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_agent_turns_session ON agent_turns(session_id, id);

-- Idempotent migrations for DBs created before these columns existed.
ALTER TABLE outreach_events ADD COLUMN IF NOT EXISTS attach_brochure INTEGER NOT NULL DEFAULT 0;
ALTER TABLE reply_analyses ADD COLUMN IF NOT EXISTS draft_pending INTEGER NOT NULL DEFAULT 0;
"""

# Tables in dependency order — used by reset_for_tests()'s TRUNCATE.
_ALL_TABLES = [
    "leads",
    "outreach_events",
    "reply_analyses",
    "settings",
    "users",
    "roles",
    "user_roles",
    "suppressions",
    "audit_log",
    "token_usage_events",
    "agent_sessions",
    "agent_turns",
]


def init_db() -> None:
    with connect() as connection:
        # psycopg allows multiple statements in one execute() when no params.
        connection.execute(_SCHEMA_DDL)
    seed_auth()


def reset_for_tests() -> None:
    """Wipe every table and re-seed default auth — per-test isolation for PG."""
    init_db()
    with connect() as connection:
        connection.execute(
            "TRUNCATE " + ", ".join(_ALL_TABLES) + " RESTART IDENTITY CASCADE"
        )
    seed_auth()


def insert_lead(lead: CandidateLead) -> dict[str, Any]:
    now = _now()
    payload = asdict(lead) | {"created_at": now, "updated_at": now}
    # Canonicalize region/country to the public standard (UN M49 regions,
    # ISO 3166-1 country names) so every write path — Agent add_leads, real web
    # search, seeds, manual — stores values that match the filter taxonomy and
    # infers the region from the country when the caller didn't set one cleanly.
    from app.geo import normalize_geo

    payload["region"], payload["country"] = normalize_geo(
        str(payload.get("region") or ""), str(payload.get("country") or "")
    )
    # Resolve and persist lead_type at insert time instead of leaving it blank
    # and re-inferring on every email render — the classification needs to be
    # a stable, queryable column for filtering/dashboards/scoring-rule choice.
    if not str(payload.get("lead_type") or "").strip():
        payload["lead_type"] = infer_lead_type(lead)
    # Every lead-creation path constructs a CandidateLead with the "new"
    # default; apply the configured score thresholds here so a lead's initial
    # status actually reflects its score instead of always starting at "new".
    if payload["status"] == "new":
        payload["status"] = status_for_score(int(payload["score"]), lead_type=payload.get("lead_type"))
    with connect() as connection:
        cursor = connection.execute(
            """
            INSERT INTO leads (
                company_name, region, country, website, contact_name, email, category,
                match_reason, source, score, status, notes, lead_type, created_at, updated_at
            )
            VALUES (
                %(company_name)s, %(region)s, %(country)s, %(website)s, %(contact_name)s, %(email)s, %(category)s,
                %(match_reason)s, %(source)s, %(score)s, %(status)s, %(notes)s, %(lead_type)s, %(created_at)s, %(updated_at)s
            )
            RETURNING id
            """,
            payload,
        )
        new_id = _scalar(cursor)
        return get_lead(new_id, connection=connection)


# Whitelist of external sort keys → SQL expressions. Values are hard-coded
# server strings, so string-interpolating them into ORDER BY is safe.
_SORT_EXPRS = {
    "id": "l.id",
    "score": "l.score",
    "company_name": "l.company_name",
    "country": "l.country",
    "region": "l.region",
    "status": "l.status",
    "category": "l.category",
    "created_at": "l.created_at",
    "updated_at": "l.updated_at",
    "reply_count": "reply_count",  # derived column, present in SELECT
}

def list_leads(
    *,
    region: str | None = None,
    country: str | None = None,
    status: str | None = None,
    lead_type: str | None = None,
    q: str | None = None,
    sort: str = "id",
    order: str = "desc",
    limit: int | None = None,
    offset: int | None = None,
) -> list[dict[str, Any]]:
    filters: list[str] = []
    params: dict[str, Any] = {}
    if region:
        filters.append("region = %(region)s")
        params["region"] = region
    if country:
        filters.append("country = %(country)s")
        params["country"] = country
    if status:
        filters.append("status = %(status)s")
        params["status"] = status
    if lead_type:
        filters.append("lead_type = %(lead_type)s")
        params["lead_type"] = lead_type
    if q:
        filters.append(
            # ILIKE, not LIKE: Postgres LIKE is case-sensitive (SQLite's was not),
            # so plain LIKE made the search box miss "Dach" for "DACH Medical" and
            # match different rows depending on the caller's capitalization.
            "(company_name ILIKE %(q)s OR email ILIKE %(q)s OR country ILIKE %(q)s OR category ILIKE %(q)s)"
        )
        params["q"] = f"%{q}%"

    where = f"WHERE {' AND '.join(filters)}" if filters else ""
    sort_key = sort if sort in _SORT_EXPRS else "id"
    sort_expr = _SORT_EXPRS[sort_key]
    sort_dir = "ASC" if str(order).lower() == "asc" else "DESC"
    # Automatic secondary sort: keep results deterministic and surface newer
    # entries within ties (unless the user is already sorting by created_at/id).
    tiebreakers: list[str] = []
    if sort_key != "created_at":
        tiebreakers.append("l.created_at DESC")
    if sort_key != "id":
        tiebreakers.append("l.id DESC")
    order_clause = f"{sort_expr} {sort_dir}"
    if tiebreakers:
        order_clause += ", " + ", ".join(tiebreakers)
    limit_clause = ""
    if limit is not None:
        limit_clause = " LIMIT %(limit)s"
        params["limit"] = max(0, int(limit))
        if offset:
            limit_clause += " OFFSET %(offset)s"
            params["offset"] = max(0, int(offset))
    with connect() as connection:
        rows = connection.execute(
            f"""SELECT l.*,
                (SELECT COUNT(*) FROM reply_analyses WHERE lead_id = l.id) AS reply_count,
                (SELECT MAX(COALESCE(NULLIF(sent_at, ''), created_at))
                   FROM outreach_events
                   WHERE lead_id = l.id AND status IN ('sent', 'queued')) AS last_outreach_at
            FROM leads l
            {where} ORDER BY {order_clause}{limit_clause}""",
            params,
        ).fetchall()
    result = [_row_to_dict(row) for row in rows]
    # Attach the AI match-level badge (strong/medium/weak), caching the two rule
    # sets so a page of leads costs at most two scoring-rule reads.
    band_cache: dict[str, list[dict[str, Any]]] = {}
    for d in result:
        lt = _normalize_scoring_lead_type(d.get("lead_type"))
        if lt not in band_cache:
            band_cache[lt] = _thresholds_for(lt)
        d["match_level"] = _level_from_bands(band_cache[lt], int(d.get("score") or 0))
    return result


def count_leads(
    *,
    region: str | None = None,
    country: str | None = None,
    status: str | None = None,
    lead_type: str | None = None,
    q: str | None = None,
) -> int:
    """Total lead count for the same filter set (ignores sort/paging).

    Used so the lead list can render a pager without the caller having to fetch
    every row. Mirrors the filter clause in `list_leads` - keep them in sync.
    """
    filters: list[str] = []
    params: dict[str, Any] = {}
    if region:
        filters.append("region = %(region)s")
        params["region"] = region
    if country:
        filters.append("country = %(country)s")
        params["country"] = country
    if status:
        filters.append("status = %(status)s")
        params["status"] = status
    if lead_type:
        filters.append("lead_type = %(lead_type)s")
        params["lead_type"] = lead_type
    if q:
        filters.append(
            # ILIKE, not LIKE: Postgres LIKE is case-sensitive (SQLite's was not),
            # so plain LIKE made the search box miss "Dach" for "DACH Medical" and
            # match different rows depending on the caller's capitalization.
            "(company_name ILIKE %(q)s OR email ILIKE %(q)s OR country ILIKE %(q)s OR category ILIKE %(q)s)"
        )
        params["q"] = f"%{q}%"
    where = f"WHERE {' AND '.join(filters)}" if filters else ""
    with connect() as connection:
        return _scalar(connection.execute(f"SELECT COUNT(*) FROM leads l {where}", params))


def get_lead(
    lead_id: int,
    *,
    connection: Connection | None = None,
) -> dict[str, Any] | None:
    if connection is not None:
        row = connection.execute("SELECT * FROM leads WHERE id = %s", (lead_id,)).fetchone()
        return _finalize_lead(_row_to_dict(row)) if row else None
    with connect() as conn:
        row = conn.execute("SELECT * FROM leads WHERE id = %s", (lead_id,)).fetchone()
        return _finalize_lead(_row_to_dict(row)) if row else None


def _finalize_lead(d: dict[str, Any]) -> dict[str, Any]:
    """Attach the AI match-level badge to a single lead dict."""
    d["match_level"] = match_level_for_score(int(d.get("score") or 0), d.get("lead_type"))
    return d


def update_lead(
    lead_id: int,
    *,
    status: str | None = None,
    notes: str | None = None,
    lead_type: str | None = None,
) -> dict[str, Any] | None:
    current = get_lead(lead_id)
    if current is None:
        return None

    updated_status = status if status is not None else current["status"]
    updated_notes = notes if notes is not None else current["notes"]
    updated_lead_type = lead_type if lead_type is not None else current["lead_type"]
    with connect() as connection:
        connection.execute(
            """
            UPDATE leads
            SET status = %s, notes = %s, lead_type = %s, updated_at = %s
            WHERE id = %s
            """,
            (updated_status, updated_notes, updated_lead_type, _now(), lead_id),
        )
        return get_lead(lead_id, connection=connection)


# Outreach sources that are REPLIES to a prospect's inbound message (not first-touch
# or follow-up cold outreach). Delivering one must not flip the lead to 'emailed'.
_REPLY_SOURCES = {"reply_draft", "reply_manual"}


def insert_outreach_event(
    lead_id: int,
    email: RenderedEmail,
    *,
    status: str = "recorded",
    message_id: str = "",
    source: str = "manual",
    attach_brochure: bool = False,
) -> dict[str, Any]:
    with connect() as connection:
        cursor = connection.execute(
            """
            INSERT INTO outreach_events (lead_id, subject, body, sent_to, region, status, message_id, source, attach_brochure, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (lead_id, email.subject, email.body, email.sent_to, email.region, status, message_id, source, int(attach_brochure), _now()),
        )
        event_id = _scalar(cursor)
        # Replies keep the lead's reply-derived status (interested/human_review/…);
        # only first-touch/follow-up cold outreach flips the lead to 'emailed'.
        if status == "sent" and source not in _REPLY_SOURCES:
            connection.execute(
                "UPDATE leads SET status = %s, updated_at = %s WHERE id = %s",
                ("emailed", _now(), lead_id),
            )
        row = connection.execute(
            "SELECT * FROM outreach_events WHERE id = %s",
            (event_id,),
        ).fetchone()
        return _row_to_dict(row)


def insert_reply_analysis(
    *,
    lead_id: int | None,
    reply_text: str,
    analysis: ReplyAnalysis,
    message_id: str = "",
    draft_pending: bool = False,
) -> dict[str, Any]:
    with connect() as connection:
        cursor = connection.execute(
            """
            INSERT INTO reply_analyses (
                lead_id, reply_text, intent, confidence, summary, next_action,
                requires_human, message_id, draft_pending, created_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (
                lead_id,
                reply_text,
                analysis.intent,
                analysis.confidence,
                analysis.summary,
                analysis.next_action,
                int(analysis.requires_human),
                message_id,
                int(draft_pending),
                _now(),
            ),
        )
        analysis_id = _scalar(cursor)
        row = connection.execute(
            "SELECT * FROM reply_analyses WHERE id = %s",
            (analysis_id,),
        ).fetchone()

    result = _row_to_dict(row)
    result["requires_human"] = bool(result["requires_human"])
    return result


def list_outreach_events(lead_id: int) -> list[dict[str, Any]]:
    with connect() as connection:
        rows = connection.execute(
            "SELECT * FROM outreach_events WHERE lead_id = %s ORDER BY id DESC",
            (lead_id,),
        ).fetchall()
    return [_row_to_dict(row) for row in rows]


def list_reply_analyses(lead_id: int) -> list[dict[str, Any]]:
    with connect() as connection:
        rows = connection.execute(
            "SELECT * FROM reply_analyses WHERE lead_id = %s ORDER BY id DESC",
            (lead_id,),
        ).fetchall()
    results = [_row_to_dict(row) for row in rows]
    for r in results:
        r["requires_human"] = bool(r["requires_human"])
    return results


def reply_analyses_awaiting_draft(limit: int = 10) -> list[dict[str, Any]]:
    """Classified replies flagged for an auto reply-draft that hasn't been
    generated yet (oldest first). Drives the background reply-draft worker."""
    with connect() as connection:
        rows = connection.execute(
            """
            SELECT * FROM reply_analyses
            WHERE draft_pending = 1 AND lead_id IS NOT NULL
            ORDER BY id ASC LIMIT %s
            """,
            (limit,),
        ).fetchall()
    results = [_row_to_dict(row) for row in rows]
    for r in results:
        r["requires_human"] = bool(r["requires_human"])
    return results


def clear_reply_draft_pending(analysis_id: int) -> None:
    with connect() as connection:
        connection.execute(
            "UPDATE reply_analyses SET draft_pending = 0 WHERE id = %s",
            (analysis_id,),
        )


def enqueue_outreach(lead_id: int, email: RenderedEmail, *, source: str = "manual") -> dict[str, Any]:
    """Queue an email for throttled background delivery (status 'queued')."""
    return insert_outreach_event(lead_id, email, status="queued", source=source)


def list_queued_events(limit: int = 50) -> list[dict[str, Any]]:
    with connect() as connection:
        rows = connection.execute(
            "SELECT * FROM outreach_events WHERE status = 'queued' ORDER BY id ASC LIMIT %s",
            (limit,),
        ).fetchall()
    return [_row_to_dict(row) for row in rows]


def count_queued() -> int:
    with connect() as connection:
        return int(_scalar(connection.execute(
            "SELECT COUNT(*) FROM outreach_events WHERE status = 'queued'"
        )))


def count_sent_since(iso_since: str, *, domain: str | None = None) -> int:
    sql = "SELECT COUNT(*) FROM outreach_events WHERE status = 'sent' AND sent_at >= %s"
    params: list[Any] = [iso_since]
    if domain:
        sql += " AND lower(sent_to) LIKE %s"
        params.append(f"%@{domain.lower()}")
    with connect() as connection:
        return int(_scalar(connection.execute(sql, params)))


def last_sent_at() -> str:
    with connect() as connection:
        value = _scalar(connection.execute(
            "SELECT MAX(sent_at) FROM outreach_events WHERE status = 'sent'"
        ))
    return value or ""


def leads_awaiting_followup() -> list[dict[str, Any]]:
    """Leads that were emailed, haven't replied, and have no pending outreach —
    candidates for a follow-up. Each row carries `sent_count` (delivered touches)
    and `last_sent` (most recent delivery) so the caller can apply the configured
    interval / max-follow-ups without extra queries."""
    with connect() as connection:
        rows = connection.execute(
            """
            SELECT l.*,
                (SELECT COUNT(*) FROM outreach_events WHERE lead_id = l.id AND status = 'sent') AS sent_count,
                (SELECT MAX(sent_at) FROM outreach_events WHERE lead_id = l.id AND status = 'sent') AS last_sent
            FROM leads l
            WHERE l.status = 'emailed'
              AND (SELECT COUNT(*) FROM reply_analyses WHERE lead_id = l.id) = 0
              AND NOT EXISTS (
                  SELECT 1 FROM outreach_events
                  WHERE lead_id = l.id AND status IN ('queued', 'draft')
              )
            """
        ).fetchall()
    return [_row_to_dict(row) for row in rows]


def mark_outreach_sent(event_id: int, *, message_id: str = "") -> dict[str, Any] | None:
    now = _now()
    with connect() as connection:
        row = connection.execute(
            "SELECT * FROM outreach_events WHERE id = %s", (event_id,)
        ).fetchone()
        if row is None:
            return None
        connection.execute(
            "UPDATE outreach_events SET status = 'sent', message_id = %s, sent_at = %s WHERE id = %s",
            (message_id, now, event_id),
        )
        # A delivered REPLY must not reset the lead to 'emailed' — it stays in its
        # reply-derived status (interested / human_review / needs_review).
        if row["source"] not in _REPLY_SOURCES:
            connection.execute(
                "UPDATE leads SET status = %s, updated_at = %s WHERE id = %s",
                ("emailed", now, row["lead_id"]),
            )
        updated = connection.execute(
            "SELECT * FROM outreach_events WHERE id = %s", (event_id,)
        ).fetchone()
    return _row_to_dict(updated)


def mark_outreach_status(event_id: int, status: str, *, error: str = "") -> None:
    with connect() as connection:
        connection.execute(
            "UPDATE outreach_events SET status = %s WHERE id = %s", (status, event_id)
        )


def list_draft_events() -> list[dict[str, Any]]:
    with connect() as connection:
        rows = connection.execute(
            """
            SELECT e.*, l.company_name, l.email AS lead_email, l.country
            FROM outreach_events e
            JOIN leads l ON e.lead_id = l.id
            WHERE e.status = 'draft'
            ORDER BY e.created_at DESC
            """
        ).fetchall()
    return [_row_to_dict(row) for row in rows]


def approve_outreach_event(event_id: int) -> dict[str, Any] | None:
    """Validate that ``event_id`` is a pending draft and return it.

    Approving does NOT mark the lead as emailed — the caller enqueues the event
    and the lead flips to ``emailed`` only when it is actually sent
    (``mark_outreach_sent``). This keeps ``emailed`` meaning "delivered", not
    "approved / queued".
    """
    with connect() as connection:
        row = connection.execute(
            "SELECT * FROM outreach_events WHERE id = %s AND status = 'draft'",
            (event_id,),
        ).fetchone()
        return _row_to_dict(row) if row else None


def reject_outreach_event(event_id: int) -> dict[str, Any] | None:
    with connect() as connection:
        row = connection.execute(
            "SELECT * FROM outreach_events WHERE id = %s AND status = 'draft'",
            (event_id,),
        ).fetchone()
        if row is None:
            return None
        connection.execute(
            "UPDATE outreach_events SET status = 'rejected' WHERE id = %s",
            (event_id,),
        )
        updated = connection.execute(
            "SELECT * FROM outreach_events WHERE id = %s", (event_id,)
        ).fetchone()
        return _row_to_dict(updated)


def update_draft_event(
    event_id: int,
    *,
    subject: str,
    body: str,
    attach_brochure: bool | None = None,
) -> dict[str, Any] | None:
    """Edit a pending draft's subject/body (and optionally the brochure flag) in
    place. Only drafts can be edited; returns None if the event isn't a draft."""
    with connect() as connection:
        row = connection.execute(
            "SELECT * FROM outreach_events WHERE id = %s AND status = 'draft'",
            (event_id,),
        ).fetchone()
        if row is None:
            return None
        if attach_brochure is None:
            connection.execute(
                "UPDATE outreach_events SET subject = %s, body = %s WHERE id = %s",
                (subject, body, event_id),
            )
        else:
            connection.execute(
                "UPDATE outreach_events SET subject = %s, body = %s, attach_brochure = %s WHERE id = %s",
                (subject, body, int(attach_brochure), event_id),
            )
        updated = connection.execute(
            "SELECT * FROM outreach_events WHERE id = %s", (event_id,)
        ).fetchone()
        return _row_to_dict(updated)


def has_pending_reply_draft(lead_id: int) -> bool:
    """True if the lead already has a reply draft awaiting send (draft or queued),
    so auto-generation doesn't pile up duplicate reply drafts on repeated syncs."""
    with connect() as connection:
        count = _scalar(connection.execute(
            """
            SELECT COUNT(*) FROM outreach_events
            WHERE lead_id = %s
              AND source IN ('reply_draft', 'reply_manual')
              AND status IN ('draft', 'queued')
            """,
            (lead_id,),
        ))
    return int(count) > 0


def latest_outreach_subject(lead_id: int) -> str | None:
    """Subject of the lead's most recent first-touch/follow-up email, for building
    a `Re: …` reply subject. Ignores prior replies."""
    with connect() as connection:
        row = connection.execute(
            """
            SELECT subject FROM outreach_events
            WHERE lead_id = %s AND source NOT IN ('reply_draft', 'reply_manual')
            ORDER BY id DESC LIMIT 1
            """,
            (lead_id,),
        ).fetchone()
    return str(row["subject"]) if row else None


def delete_lead(lead_id: int) -> bool:
    with connect() as connection:
        # Delete children first: PostgreSQL enforces the outreach_events /
        # reply_analyses → leads foreign keys, so the parent row can't go first.
        connection.execute("DELETE FROM outreach_events WHERE lead_id = %s", (lead_id,))
        connection.execute("DELETE FROM reply_analyses WHERE lead_id = %s", (lead_id,))
        cursor = connection.execute("DELETE FROM leads WHERE id = %s", (lead_id,))
        return cursor.rowcount > 0


def metrics() -> dict[str, int]:
    with connect() as connection:
        total_leads = _scalar(connection.execute("SELECT COUNT(*) FROM leads"))
        interested = _scalar(connection.execute(
            "SELECT COUNT(*) FROM leads WHERE status = 'interested'"
        ))
        # Count LEADS currently in the 'emailed' pipeline stage — consistent with
        # the sibling metrics (interested / human_review) and with the status
        # filter. (It used to COUNT(*) every outreach_events row, which counted
        # drafts/queued/reply-drafts as "sent" and never matched the filter.)
        emailed = _scalar(connection.execute(
            "SELECT COUNT(*) FROM leads WHERE status = 'emailed'"
        ))
        human_review = _scalar(connection.execute(
            "SELECT COUNT(*) FROM leads WHERE status = 'human_review'"
        ))
        distributor_leads = _scalar(connection.execute(
            "SELECT COUNT(*) FROM leads WHERE lead_type = 'distributor'"
        ))
        kol_leads = _scalar(connection.execute(
            "SELECT COUNT(*) FROM leads WHERE lead_type = 'kol'"
        ))
        distributor_qualified = _scalar(connection.execute(
            "SELECT COUNT(*) FROM leads WHERE lead_type = 'distributor' AND status = 'qualified'"
        ))
        kol_qualified = _scalar(connection.execute(
            "SELECT COUNT(*) FROM leads WHERE lead_type = 'kol' AND status = 'qualified'"
        ))
    return {
        "total_leads": total_leads,
        "interested_leads": interested,
        "emailed_leads": emailed,
        "human_review": human_review,
        "distributor_leads": distributor_leads,
        "kol_leads": kol_leads,
        "distributor_qualified": distributor_qualified,
        "kol_qualified": kol_qualified,
    }


def lead_facets() -> dict[str, list[dict[str, Any]]]:
    """Distinct region/country values (with counts) across all leads.

    Powers the lead-management filter dropdowns so users can only filter by
    values that actually exist. Computed over every lead (ignores the active
    filter) so switching filters always shows the full option set.
    """
    with connect() as connection:
        region_rows = connection.execute(
            """
            SELECT region AS value, COUNT(*) AS count FROM leads
            WHERE TRIM(region) <> '' GROUP BY region ORDER BY count DESC, region ASC
            """
        ).fetchall()
        country_rows = connection.execute(
            """
            SELECT country AS value, COUNT(*) AS count FROM leads
            WHERE TRIM(country) <> '' GROUP BY country ORDER BY count DESC, country ASC
            """
        ).fetchall()
    return {
        "regions": [{"value": row["value"], "count": int(row["count"])} for row in region_rows],
        "countries": [{"value": row["value"], "count": int(row["count"])} for row in country_rows],
    }


# ── Token usage (AI cost monitoring) ───────────────────

def insert_token_usage_event(
    *,
    source: str,
    provider: str,
    model: str,
    prompt_tokens: int,
    completion_tokens: int,
    total_tokens: int,
    actor: str = "",
) -> None:
    with connect() as connection:
        connection.execute(
            """
            INSERT INTO token_usage_events (
                source, provider, model, prompt_tokens, completion_tokens, total_tokens, actor, created_at
            )
            VALUES (%(source)s, %(provider)s, %(model)s, %(prompt_tokens)s, %(completion_tokens)s, %(total_tokens)s, %(actor)s, %(created_at)s)
            """,
            {
                "source": source,
                "provider": provider,
                "model": model,
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "total_tokens": total_tokens,
                "actor": actor,
                "created_at": _now(),
            },
        )


def token_usage_total_since(iso_since: str) -> int:
    with connect() as connection:
        value = _scalar(connection.execute(
            "SELECT COALESCE(SUM(total_tokens), 0) FROM token_usage_events WHERE created_at >= %s",
            (iso_since,),
        ))
    return int(value)


def token_usage_breakdown_since(iso_since: str) -> dict[str, int]:
    with connect() as connection:
        rows = connection.execute(
            """
            SELECT source, COALESCE(SUM(total_tokens), 0) AS total
            FROM token_usage_events WHERE created_at >= %s
            GROUP BY source
            """,
            (iso_since,),
        ).fetchall()
    return {row["source"]: int(row["total"]) for row in rows}


def token_usage_daily_series(*, since_iso: str) -> list[dict[str, Any]]:
    with connect() as connection:
        rows = connection.execute(
            """
            SELECT substr(created_at, 1, 10) AS day, COALESCE(SUM(total_tokens), 0) AS total
            FROM token_usage_events
            WHERE created_at >= %s
            GROUP BY day
            ORDER BY day ASC
            """,
            (since_iso,),
        ).fetchall()
    return [{"date": row["day"], "total_tokens": int(row["total"])} for row in rows]


def _row_to_dict(row: dict[str, Any]) -> dict[str, Any]:
    return dict(row)


# ── Auth: users, roles, RBAC ───────────────────────────

def seed_auth() -> None:
    """Seed default roles and a superadmin on first run (idempotent)."""
    from app.auth import (
        DEFAULT_ADMIN_PASSWORD,
        DEFAULT_ADMIN_USERNAME,
        DEFAULT_ROLES,
        hash_password,
    )

    with connect() as connection:
        existing_roles = {
            row["name"] for row in connection.execute("SELECT name FROM roles").fetchall()
        }
        for role in DEFAULT_ROLES:
            if role["name"] in existing_roles:
                continue
            connection.execute(
                """
                INSERT INTO roles (name, description, permissions, is_system, created_at, updated_at)
                VALUES (%s, %s, %s, 1, %s, %s)
                """,
                (
                    role["name"],
                    role["description"],
                    json.dumps(role["permissions"]),
                    _now(),
                    _now(),
                ),
            )

        user_count = _scalar(connection.execute("SELECT COUNT(*) FROM users"))
        if user_count == 0:
            cursor = connection.execute(
                """
                INSERT INTO users (username, password_hash, display_name, is_active, is_superadmin, must_change_password, created_at, updated_at)
                VALUES (%s, %s, %s, 1, 1, 1, %s, %s)
                RETURNING id
                """,
                (
                    DEFAULT_ADMIN_USERNAME,
                    hash_password(DEFAULT_ADMIN_PASSWORD),
                    "系统管理员",
                    _now(),
                    _now(),
                ),
            )
            admin_id = _scalar(cursor)
            admin_role = connection.execute(
                "SELECT id FROM roles WHERE name = %s", ("管理员",)
            ).fetchone()
            if admin_role:
                connection.execute(
                    "INSERT INTO user_roles (user_id, role_id) VALUES (%s, %s) ON CONFLICT DO NOTHING",
                    (admin_id, admin_role["id"]),
                )


def _role_to_dict(row: dict[str, Any]) -> dict[str, Any]:
    data = dict(row)
    try:
        data["permissions"] = json.loads(data.get("permissions") or "[]")
    except (ValueError, TypeError):
        data["permissions"] = []
    data["is_system"] = bool(data.get("is_system"))
    return data


def list_roles() -> list[dict[str, Any]]:
    with connect() as connection:
        rows = connection.execute(
            """
            SELECT r.*, (SELECT COUNT(*) FROM user_roles WHERE role_id = r.id) AS user_count
            FROM roles r ORDER BY r.id
            """
        ).fetchall()
    return [_role_to_dict(row) for row in rows]


def get_role(role_id: int) -> dict[str, Any] | None:
    with connect() as connection:
        row = connection.execute("SELECT * FROM roles WHERE id = %s", (role_id,)).fetchone()
    return _role_to_dict(row) if row else None


def get_role_by_name(name: str) -> dict[str, Any] | None:
    with connect() as connection:
        row = connection.execute("SELECT * FROM roles WHERE name = %s", (name,)).fetchone()
    return _role_to_dict(row) if row else None


def create_role(*, name: str, description: str, permissions: list[str]) -> dict[str, Any]:
    with connect() as connection:
        cursor = connection.execute(
            """
            INSERT INTO roles (name, description, permissions, is_system, created_at, updated_at)
            VALUES (%s, %s, %s, 0, %s, %s)
            RETURNING id
            """,
            (name, description, json.dumps(permissions), _now(), _now()),
        )
        role_id = _scalar(cursor)
        row = connection.execute(
            "SELECT * FROM roles WHERE id = %s", (role_id,)
        ).fetchone()
    return _role_to_dict(row)


def update_role(
    role_id: int,
    *,
    name: str | None = None,
    description: str | None = None,
    permissions: list[str] | None = None,
) -> dict[str, Any] | None:
    current = get_role(role_id)
    if current is None:
        return None
    new_name = name if name is not None else current["name"]
    new_desc = description if description is not None else current["description"]
    new_perms = permissions if permissions is not None else current["permissions"]
    with connect() as connection:
        connection.execute(
            "UPDATE roles SET name = %s, description = %s, permissions = %s, updated_at = %s WHERE id = %s",
            (new_name, new_desc, json.dumps(new_perms), _now(), role_id),
        )
    return get_role(role_id)


def delete_role(role_id: int) -> bool:
    with connect() as connection:
        cursor = connection.execute(
            "DELETE FROM roles WHERE id = %s AND is_system = 0", (role_id,)
        )
        if cursor.rowcount == 0:
            return False
        connection.execute("DELETE FROM user_roles WHERE role_id = %s", (role_id,))
        return True


def _user_to_dict(row: dict[str, Any], *, roles: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    data = dict(row)
    data.pop("password_hash", None)
    data["is_active"] = bool(data.get("is_active"))
    data["is_superadmin"] = bool(data.get("is_superadmin"))
    data["must_change_password"] = bool(data.get("must_change_password"))
    if roles is not None:
        data["roles"] = [{"id": r["id"], "name": r["name"]} for r in roles]
        if data["is_superadmin"]:
            from app.auth import PERMISSION_KEYS

            data["permissions"] = sorted(PERMISSION_KEYS)
        else:
            perms: set[str] = set()
            for r in roles:
                perms.update(r["permissions"])
            data["permissions"] = sorted(perms)
    return data


def _roles_for_user(connection: Connection, user_id: int) -> list[dict[str, Any]]:
    rows = connection.execute(
        """
        SELECT r.* FROM roles r
        JOIN user_roles ur ON ur.role_id = r.id
        WHERE ur.user_id = %s ORDER BY r.id
        """,
        (user_id,),
    ).fetchall()
    return [_role_to_dict(row) for row in rows]


def list_users() -> list[dict[str, Any]]:
    with connect() as connection:
        rows = connection.execute("SELECT * FROM users ORDER BY id").fetchall()
        return [
            _user_to_dict(row, roles=_roles_for_user(connection, row["id"])) for row in rows
        ]


def get_user(user_id: int) -> dict[str, Any] | None:
    with connect() as connection:
        row = connection.execute("SELECT * FROM users WHERE id = %s", (user_id,)).fetchone()
        if row is None:
            return None
        return _user_to_dict(row, roles=_roles_for_user(connection, user_id))


def get_user_auth_row(username: str) -> dict[str, Any] | None:
    """Return the raw user row (including password_hash) for login verification."""
    with connect() as connection:
        row = connection.execute(
            "SELECT * FROM users WHERE username = %s", (username,)
        ).fetchone()
    return dict(row) if row else None


def get_user_principal(user_id: int):
    """Build an auth.Principal for an active user, or None if missing/inactive."""
    from app.auth import Principal

    with connect() as connection:
        row = connection.execute("SELECT * FROM users WHERE id = %s", (user_id,)).fetchone()
        if row is None or not row["is_active"]:
            return None
        roles = _roles_for_user(connection, user_id)

    perms: set[str] = set()
    for r in roles:
        perms.update(r["permissions"])
    return Principal(
        user_id=int(row["id"]),
        username=str(row["username"]),
        permissions=frozenset(perms),
        is_superadmin=bool(row["is_superadmin"]),
    )


def create_user(
    *,
    username: str,
    password: str,
    display_name: str = "",
    is_active: bool = True,
    is_superadmin: bool = False,
    role_ids: list[int] | None = None,
    must_change_password: bool = True,
) -> dict[str, Any]:
    from app.auth import hash_password

    with connect() as connection:
        cursor = connection.execute(
            """
            INSERT INTO users (username, password_hash, display_name, is_active, is_superadmin, must_change_password, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (
                username,
                hash_password(password),
                display_name,
                int(is_active),
                int(is_superadmin),
                int(must_change_password),
                _now(),
                _now(),
            ),
        )
        user_id = _scalar(cursor)
        for rid in role_ids or []:
            connection.execute(
                "INSERT INTO user_roles (user_id, role_id) VALUES (%s, %s) ON CONFLICT DO NOTHING",
                (user_id, rid),
            )
    return get_user(user_id)


def update_user(
    user_id: int,
    *,
    display_name: str | None = None,
    is_active: bool | None = None,
    is_superadmin: bool | None = None,
    role_ids: list[int] | None = None,
) -> dict[str, Any] | None:
    current = get_user(user_id)
    if current is None:
        return None
    new_name = display_name if display_name is not None else current["display_name"]
    new_active = is_active if is_active is not None else current["is_active"]
    new_super = is_superadmin if is_superadmin is not None else current["is_superadmin"]
    with connect() as connection:
        connection.execute(
            "UPDATE users SET display_name = %s, is_active = %s, is_superadmin = %s, updated_at = %s WHERE id = %s",
            (new_name, int(new_active), int(new_super), _now(), user_id),
        )
        if role_ids is not None:
            connection.execute("DELETE FROM user_roles WHERE user_id = %s", (user_id,))
            for rid in role_ids:
                connection.execute(
                    "INSERT INTO user_roles (user_id, role_id) VALUES (%s, %s) ON CONFLICT DO NOTHING",
                    (user_id, rid),
                )
    return get_user(user_id)


def set_user_password(user_id: int, password: str, *, must_change: bool = False) -> bool:
    from app.auth import hash_password

    with connect() as connection:
        cursor = connection.execute(
            "UPDATE users SET password_hash = %s, must_change_password = %s, updated_at = %s WHERE id = %s",
            (hash_password(password), int(must_change), _now(), user_id),
        )
        return cursor.rowcount > 0


def delete_user(user_id: int) -> bool:
    with connect() as connection:
        cursor = connection.execute("DELETE FROM users WHERE id = %s", (user_id,))
        if cursor.rowcount == 0:
            return False
        connection.execute("DELETE FROM user_roles WHERE user_id = %s", (user_id,))
        return True


def count_active_superadmins(exclude_user_id: int | None = None) -> int:
    with connect() as connection:
        if exclude_user_id is None:
            value = _scalar(connection.execute(
                "SELECT COUNT(*) FROM users WHERE is_superadmin = 1 AND is_active = 1"
            ))
        else:
            value = _scalar(connection.execute(
                "SELECT COUNT(*) FROM users WHERE is_superadmin = 1 AND is_active = 1 AND id != %s",
                (exclude_user_id,),
            ))
    return int(value)


# ── Suppression list (do-not-email) ────────────────────

def add_suppression(email: str, *, reason: str = "unsubscribe", source: str = "", notes: str = "") -> dict[str, Any]:
    norm = email.strip().lower()
    with connect() as connection:
        connection.execute(
            """
            INSERT INTO suppressions (email, reason, source, notes, created_at)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT(email) DO UPDATE SET reason = excluded.reason, source = excluded.source
            """,
            (norm, reason, source, notes, _now()),
        )
        row = connection.execute("SELECT * FROM suppressions WHERE email = %s", (norm,)).fetchone()
    return _row_to_dict(row)


def is_suppressed(email: str) -> bool:
    norm = email.strip().lower()
    if not norm:
        return False
    with connect() as connection:
        row = connection.execute(
            "SELECT 1 FROM suppressions WHERE email = %s LIMIT 1", (norm,)
        ).fetchone()
    return row is not None


def list_suppressions(q: str | None = None) -> list[dict[str, Any]]:
    with connect() as connection:
        if q:
            rows = connection.execute(
                "SELECT * FROM suppressions WHERE email LIKE %s ORDER BY id DESC",
                (f"%{q.strip().lower()}%",),
            ).fetchall()
        else:
            rows = connection.execute(
                "SELECT * FROM suppressions ORDER BY id DESC"
            ).fetchall()
    return [_row_to_dict(row) for row in rows]


def remove_suppression(email: str) -> bool:
    norm = email.strip().lower()
    with connect() as connection:
        cursor = connection.execute("DELETE FROM suppressions WHERE email = %s", (norm,))
        return cursor.rowcount > 0


# ── Audit log ──────────────────────────────────────────

def add_audit(
    *,
    actor: str,
    action: str,
    target_type: str = "",
    target_id: str | int = "",
    detail: str = "",
) -> None:
    with connect() as connection:
        connection.execute(
            """
            INSERT INTO audit_log (actor, action, target_type, target_id, detail, created_at)
            VALUES (%s, %s, %s, %s, %s, %s)
            """,
            (actor, action, target_type, str(target_id), detail, _now()),
        )


def list_audit(*, limit: int = 200, action: str | None = None, actor: str | None = None) -> list[dict[str, Any]]:
    filters: list[str] = []
    params: list[Any] = []
    if action:
        filters.append("action = %s")
        params.append(action)
    if actor:
        filters.append("actor = %s")
        params.append(actor)
    where = f"WHERE {' AND '.join(filters)}" if filters else ""
    params.append(max(1, min(limit, 1000)))
    with connect() as connection:
        rows = connection.execute(
            f"SELECT * FROM audit_log {where} ORDER BY id DESC LIMIT %s", params
        ).fetchall()
    return [_row_to_dict(row) for row in rows]


# ── Settings ───────────────────────────────────────────

# Settings whose values are encrypted at rest (transparently de/encrypted here).
_SECRET_SETTING_KEYS = {"agent_key", "email_password"}


def get_setting(key: str, default: str = "") -> str:
    with connect() as connection:
        row = connection.execute(
            "SELECT value FROM settings WHERE key = %s", (key,)
        ).fetchone()
    if not row:
        return default
    value = row["value"]
    if key in _SECRET_SETTING_KEYS:
        from app.crypto import decrypt_secret

        return decrypt_secret(value)
    return value


def set_setting(key: str, value: str) -> None:
    if key in _SECRET_SETTING_KEYS and value:
        from app.crypto import encrypt_secret

        value = encrypt_secret(value)
    with connect() as connection:
        connection.execute(
            "INSERT INTO settings (key, value) VALUES (%s, %s) "
            "ON CONFLICT(key) DO UPDATE SET value = excluded.value",
            (key, value),
        )


def get_all_settings() -> dict[str, str]:
    with connect() as connection:
        rows = connection.execute("SELECT key, value FROM settings").fetchall()
    from app.crypto import decrypt_secret

    result: dict[str, str] = {}
    for row in rows:
        key, value = row["key"], row["value"]
        result[key] = decrypt_secret(value) if key in _SECRET_SETTING_KEYS else value
    return result


# ── Lead scoring rules ───────────────────────────────────
# Stored as a JSON blob per lead_type under the settings table. Defaults
# mirror the overseas-distributor-prospecting SKILL.md Step 5 rules verbatim,
# so behavior is unchanged until an admin actually customizes them.
#
# "scoring_rules" is the legacy single-set key (pre-dates the distributor/KOL
# split) and is kept as the distributor key so any rules an admin already
# customized are not silently discarded.

_SCORING_RULES_SETTING_KEYS = {
    "distributor": "scoring_rules",
    "kol": "scoring_rules_kol",
}

DEFAULT_SCORING_RULES: dict[str, Any] = {
    "weights": [
        {"key": "channel_fit", "label": "渠道匹配度", "percent": 40},
        {"key": "market_priority", "label": "目标市场战略优先级", "percent": 25},
        {"key": "academic_brand", "label": "学术/品牌公开资历", "percent": 20},
        {"key": "contact_availability", "label": "联系方式可用性", "percent": 10},
        {"key": "kol_hospital_evidence", "label": "公开KOL/医院合作记录（加分项）", "percent": 5},
    ],
    "positive_rules": [
        {"points": 25, "description": "官网确认从事医疗器械分销、进口或渠道销售"},
        {"points": 20, "description": "明确的骨科植入物/关节置换/膝关节置换/手术设备/机器人/导航/OR资本设备相关性"},
        {"points": 15, "description": "有可见的商务邮箱或官方联系表单"},
        {"points": 15, "description": "公司所在国家/区域覆盖匹配目标市场"},
        {"points": 10, "description": "有具名的商务拓展/销售/产品/经销联系人"},
        {"points": 10, "description": "出现在厂商合作伙伴页、官方展商名录、监管/进口商目录，或医疗器械协会目录中"},
        {"points": 5, "description": "具备与目标区域相关的多国覆盖"},
    ],
    "negative_rules": [
        {"points": -20, "description": "来源证据薄弱或不完整"},
        {"points": -20, "description": "仅有LinkedIn/社交媒体/贸易目录证据，无官网确认"},
        {"points": -30, "description": "与医疗机器人、骨科器械、医疗分销、手术设备或医院设备无关"},
        {"points": -30, "description": "疑似仅为医院、媒体、咨询公司、招聘网站、消费品，或无关的工业机器人公司"},
        {"points": -40, "description": "确认为重复线索"},
    ],
    "thresholds": [
        {"min": 80, "max": 100, "level": "strong", "label": "强匹配"},
        {"min": 60, "max": 79, "level": "medium", "label": "中匹配"},
        {"min": 40, "max": 59, "level": "weak", "label": "弱匹配"},
        {"min": 0, "max": 39, "level": "reject", "label": "建议拒绝"},
    ],
}

# Mirrors SKILL.md Step 5 "KOL-specific scoring" — distinct from the
# distributor rules above because the evidence that matters for a surgeon
# (case volume, robotic experience, academic output) is nothing like what
# matters for a distribution company.
DEFAULT_KOL_SCORING_RULES: dict[str, Any] = {
    "weights": [
        {"key": "clinical_volume_fit", "label": "临床/手术量匹配度", "percent": 40},
        {"key": "market_priority", "label": "目标市场战略优先级", "percent": 25},
        {"key": "academic_brand", "label": "学术/品牌公开资历", "percent": 20},
        {"key": "contact_availability", "label": "联系方式可用性", "percent": 10},
        {"key": "mentorship_evidence", "label": "带教/机构合作证据（加分项）", "percent": 5},
    ],
    "positive_rules": [
        {"points": 25, "description": "手术量证据充分（约150+ TKA/年）或有机器人/导航手术经验"},
        {"points": 20, "description": "有'首例'类里程碑成就（本国/本地区首例机器人或导航手术等）"},
        {"points": 15, "description": "有学术产出：骨科期刊发表论文，或具名教授/研究职称"},
        {"points": 15, "description": "有会议/同行影响力：AAOS/AAHKS/CAOS 或区域关节置换学会演讲者，或学会任职"},
        {"points": 10, "description": "任职于教学医院、学术医学中心或专科培训项目"},
        {"points": 10, "description": "有带教、培训同行或接待观摩医生的记录"},
        {"points": 10, "description": "有可见的商务/专业邮箱或官方联系方式"},
        {"points": 5, "description": "所在机构或职务覆盖战略优先目标市场"},
    ],
    "negative_rules": [
        {"points": -20, "description": "来源证据薄弱或间接（仅医院人员名录，无手术/学术细节）"},
        {"points": -30, "description": "无手术量、机器人/导航经验或学术产出证据，缺乏可个性化的信息"},
        {"points": -40, "description": "确认为重复线索"},
    ],
    "thresholds": [
        {"min": 80, "max": 100, "level": "strong", "label": "强匹配"},
        {"min": 60, "max": 79, "level": "medium", "label": "中匹配"},
        {"min": 40, "max": 59, "level": "weak", "label": "弱匹配"},
        {"min": 0, "max": 39, "level": "reject", "label": "建议拒绝"},
    ],
}

DEFAULT_SCORING_RULES_BY_TYPE: dict[str, dict[str, Any]] = {
    "distributor": DEFAULT_SCORING_RULES,
    "kol": DEFAULT_KOL_SCORING_RULES,
}


def _normalize_scoring_lead_type(lead_type: str | None) -> str:
    return "kol" if str(lead_type or "").strip().lower() == "kol" else "distributor"


def get_scoring_rules(lead_type: str | None = None) -> dict[str, Any]:
    normalized = _normalize_scoring_lead_type(lead_type)
    setting_key = _SCORING_RULES_SETTING_KEYS[normalized]
    defaults = DEFAULT_SCORING_RULES_BY_TYPE[normalized]
    raw = get_setting(setting_key, "")
    if not raw:
        return {**defaults, "updated_at": ""}
    try:
        parsed = json.loads(raw)
    except (ValueError, TypeError):
        return {**defaults, "updated_at": ""}
    parsed.setdefault("updated_at", "")
    return parsed


# Legacy threshold configs stored a pipeline `status` per band; the model now
# stores a match `level` (strong/medium/weak/reject) that is decoupled from the
# pipeline status. Map old values so previously-saved custom rules keep working.
_LEGACY_STATUS_TO_LEVEL = {
    "qualified": "strong",
    "new": "medium",
    "human_review": "weak",
    "rejected": "reject",
}


def _thresholds_for(lead_type: str | None) -> list[dict[str, Any]]:
    normalized = _normalize_scoring_lead_type(lead_type)
    return get_scoring_rules(normalized).get("thresholds") or DEFAULT_SCORING_RULES_BY_TYPE[normalized]["thresholds"]


def _level_from_bands(thresholds: list[dict[str, Any]], score: int) -> str:
    """Return the match level ('strong'|'medium'|'weak'|'reject') for a score."""
    for rule in thresholds:
        try:
            lo, hi = int(rule["min"]), int(rule["max"])
        except (KeyError, TypeError, ValueError):
            continue
        if lo <= score <= hi:
            level = str(rule.get("level") or "").strip()
            return level or _LEGACY_STATUS_TO_LEVEL.get(str(rule.get("status") or "").strip(), "")
    return ""


def match_level_for_score(score: int, lead_type: str | None = None) -> str:
    """AI match-strength badge, independent of pipeline status.

    Returns 'strong' | 'medium' | 'weak' | 'reject' | '' — surfaced in the UI as
    a 匹配度 tag so the score still informs the user without masquerading as a
    workflow state.
    """
    return _level_from_bands(_thresholds_for(lead_type), int(score))


def _auto_confirm_strong() -> bool:
    return get_setting("auto_confirm_strong", "false") == "true"


def status_for_score(score: int, lead_type: str | None = None) -> str:
    """Map a score to an initial PIPELINE status — decoupled from match level.

    Scoring only ever produces three pipeline states:
      • 'rejected'  — score falls in the reject band
      • 'qualified' — strong match AND the 强匹配自动确认 toggle is on
      • 'pending'   — everything else, awaiting human confirmation

    The strong/medium/weak distinction is carried by match_level_for_score, not
    the status, so users see a single 待确认 queue instead of two look-alike
    "needs review" statuses (the old 'new' + 'human_review')."""
    level = match_level_for_score(score, lead_type)
    if level == "reject":
        return "rejected"
    if level == "strong" and _auto_confirm_strong():
        return "qualified"
    return "pending"


def set_scoring_rules(rules: dict[str, Any], lead_type: str | None = None) -> dict[str, Any]:
    normalized = _normalize_scoring_lead_type(lead_type)
    setting_key = _SCORING_RULES_SETTING_KEYS[normalized]
    payload = {**rules, "updated_at": _now()}
    set_setting(setting_key, json.dumps(payload))
    return payload


# ── Agent chat (team-shared) ───────────────────────────

def upsert_agent_session(
    session_id: str, *, title: str | None = None, actor: str = ""
) -> dict[str, Any]:
    """Create the session on first use, otherwise bump its activity time. A
    provided title overwrites (renames); omitting it leaves the title alone."""
    now = _now()
    with connect() as connection:
        connection.execute(
            """
            INSERT INTO agent_sessions (session_id, title, created_by, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (session_id) DO UPDATE SET updated_at = EXCLUDED.updated_at
            """,
            (session_id, title or "", actor, now, now),
        )
        if title is not None:
            connection.execute(
                "UPDATE agent_sessions SET title = %s, updated_at = %s WHERE session_id = %s",
                (title, now, session_id),
            )
        row = connection.execute(
            "SELECT * FROM agent_sessions WHERE session_id = %s", (session_id,)
        ).fetchone()
    return _row_to_dict(row)


def list_agent_sessions(limit: int = 200) -> list[dict[str, Any]]:
    """Every agent session (team-shared), most recently active first."""
    with connect() as connection:
        rows = connection.execute(
            """
            SELECT s.*,
                (SELECT COUNT(*) FROM agent_turns t WHERE t.session_id = s.session_id) AS turn_count
            FROM agent_sessions s
            ORDER BY s.updated_at DESC
            LIMIT %s
            """,
            (limit,),
        ).fetchall()
    return [_row_to_dict(row) for row in rows]


def get_agent_session(session_id: str) -> dict[str, Any] | None:
    with connect() as connection:
        row = connection.execute(
            "SELECT * FROM agent_sessions WHERE session_id = %s", (session_id,)
        ).fetchone()
    return _row_to_dict(row) if row else None


def list_agent_turns(session_id: str) -> list[dict[str, Any]]:
    """Turns of one session, oldest first. `payload` is decoded back to a dict."""
    with connect() as connection:
        rows = connection.execute(
            "SELECT * FROM agent_turns WHERE session_id = %s ORDER BY id ASC",
            (session_id,),
        ).fetchall()
    results: list[dict[str, Any]] = []
    for row in rows:
        item = _row_to_dict(row)
        try:
            item["payload"] = json.loads(item["payload"])
        except (ValueError, TypeError):
            item["payload"] = {}
        results.append(item)
    return results


def insert_agent_turn(
    session_id: str, *, payload: dict[str, Any], author: str = ""
) -> dict[str, Any]:
    now = _now()
    with connect() as connection:
        cursor = connection.execute(
            """
            INSERT INTO agent_turns (session_id, author, payload, created_at)
            VALUES (%s, %s, %s, %s)
            RETURNING id
            """,
            (session_id, author, json.dumps(payload, ensure_ascii=False), now),
        )
        turn_id = _scalar(cursor)
        connection.execute(
            "UPDATE agent_sessions SET updated_at = %s WHERE session_id = %s",
            (now, session_id),
        )
        row = connection.execute(
            "SELECT * FROM agent_turns WHERE id = %s", (turn_id,)
        ).fetchone()
    item = _row_to_dict(row)
    item["payload"] = payload
    return item


def delete_agent_session(session_id: str) -> bool:
    """Delete a session and its turns (children first — PG enforces order)."""
    with connect() as connection:
        row = connection.execute(
            "SELECT id FROM agent_sessions WHERE session_id = %s", (session_id,)
        ).fetchone()
        if row is None:
            return False
        connection.execute("DELETE FROM agent_turns WHERE session_id = %s", (session_id,))
        connection.execute("DELETE FROM agent_sessions WHERE session_id = %s", (session_id,))
    return True


# ── Helpers ────────────────────────────────────────────

def _now() -> str:
    return datetime.now(UTC).isoformat()
